cathayddt/bdk

ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md

+ 新增 ISSUE_TEMPLATE.md
+ 更改 PULL_REQUEST_TEMPLATE.md 
* OS:
* NPM Version:

Add issue template

---

README.md
src/instance/infra/docker/runner.ts

解決dockerode不會自動下載image的問題
* OS:
* NPM Version:

Docker image prerequisites

---

src/instance/infra/docker/runner.ts

dockeroder 在 pull 的時候，不會等 pull 完成，需要自行 pending 檢查
* OS: ubuntu
* NodeJS Version: 12
* NPM Version: 7
* Docker Version: 20

Fix dockerode pull issue

---

EXAMPLE-EN.md
package-lock.json
src/model/prompts/util.ts

Fix for Issue #11 
- #11 
* OS:
* NPM Version:

Fix help text errors

---

EXAMPLE-EN.md
package-lock.json

Finish English docs translation
* OS:
* NPM Version:

Finish translating the English example docs

---

package-lock.json

請簡單說明此PR的更動、被修復的問題以及相關的原因，並請列出這個更動所需要的任何相依模組/套件。
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- #(issue1)
- #(issue2)
- #(issue3)
* OS:
* NPM Version:

Upgrade package-lock.json to lockfileVersion 2

---

src/console.ts

npm version >= 7.x 時， npm link 會成為 Global link。所以在開發時重新 link 時，需要先 unlink 才能刪除 dist/。
* OS: mac
* NodeJS Version: 16.13.1
* NPM Version: 8.2.0

Fix npm link step in "npm run start:dev" && "npm run build:console"

---

src/instance/fabricInstance.ts

fix bug: command use 'peer' rather than OrgTypeEnum.PEER

---

cicd/test_script/crypto-gen.sh
docs/EXAMPLE-EN.md
docs/EXAMPLE.md
src/command/org/peer/add-system-channel.ts
src/command/org/peer/update.ts
src/instance/fabricInstance.ts
src/model/type/channel.type.ts
src/model/type/peer.type.ts
src/service/channel.ts
src/service/orderer.ts
src/service/peer.ts

將新的peer org加到system-channel
- 新加入的peer org無法創建channel
* OS: Ubuntu 20.04.3 LTS (GNU/Linux 5.11.0-1020-gcp x86_64)
* NodeJS Version: v16.13.1
* NPM Version: 8.2.0
* Docker Version: 20.10.9

bdk org peer add-system-channel

---

cicd/test_script/steps/test-new-org.sh
src/instance/bdkFile.ts
src/service/network.ts
src/service/orderer.ts
src/service/peer.ts

修正 issue #38
- #38 
- #43 
* OS:
* NPM Version:

`bdk network create` 產出 org definition json 檔

---

src/service/channel.ts

ChannelService的approve與update是類別的method，不應該寫成箭頭函數
* OS:
* NPM Version:

fix: channelService 的 approve 與 update 不應該使用箭頭函數

---

src/service/channel.ts

其他Steps中同樣的方法皆命名為fetchChannelConfig
https://github.com/kth-tw/bdk/blob/2a9e8c35e4f3c00ef531b987fc23865205064447/src/service/orderer.ts#L191-L194
* OS:
* NPM Version:

rename updateAnchorPeerSteps fetchChannelBlock to fetchChannelConfig 

---

src/instance/bdkFile.ts
src/service/channel.ts

1. createChannelArtifact 改名成 createChannelArtifactFolder
2. should createChannelArtifactFolder before convertChannelConfigtxToTx
* OS:
* NPM Version:

Fix bug: should createChannelArtifactFolder before convertChannelConfigtxToTx

---

src/service/channel.ts
src/service/orderer.ts
src/service/peer.ts

大部分情況下，`signType`都是吃`this.config.orgType`，將此值設為預設值
* OS:
* NPM Version:

refactor: channelService fetchChannelConfig have default signType value

---

README.md
docs/COMMANDS.md
src/command/hello.ts
src/service/hello.ts
test/service/hello.test.ts

更新 `bdk hello` 的輸出結果
輸出為
```
You have installed bdk successfully!!!
```
- #59 
* OS:
* NPM Version:

Update command `bdk hello` output and update README.md

---

test/service/chaincode.test.ts

unit test chaincode的timeout太短，改成90秒
* OS:
* NPM Version:

fix unit test timeout

---

CHANGELOG.md
MAINTAINERS.md
README.md
docs/fabric/COMMANDS.md
docs/quorum/COMMANDS.md
docs/quorum/EXAMPLE.md
package-lock.json
package.json
sonar-project.properties

1. 將版本號修改為 `v2.0.0`
2. 新增 Quorum 指令文件以及範例文件
3. 新增 Maintainers 資料
4. 新增變更紀錄
- Quorum 文件未更新
* OS: macOS 12.5.1
* Docker Version: 20.10.17

Update: Quorum Docs Update

---

.github/CODEOWNERS
CHANGELOG.md
README.md
docs/quorum/COMMANDS.md
docs/quorum/EXAMPLE.md
package-lock.json
package.json
src/quorum/command/backup.ts
src/quorum/command/backup/export.ts
src/quorum/command/backup/import.ts
src/quorum/command/explorer/create.ts
src/quorum/command/network/create.ts
src/quorum/command/network/down.ts
src/quorum/command/network/up.ts
src/quorum/instance/bdkFile.ts
src/quorum/instance/infra/InfraRunner.interface.ts
src/quorum/instance/infra/docker/runner.ts
src/quorum/instance/member.ts
src/quorum/instance/validator.ts
src/quorum/model/yaml/docker-compose/explorerDockerComposeYaml.ts
src/quorum/model/yaml/docker-compose/memberDockerCompose.ts
src/quorum/model/yaml/docker-compose/validatorDockerComposeYaml.ts
src/quorum/service/backup.ts
src/quorum/service/network.ts
src/util/error.ts
src/util/utils.ts

1. 新增 Quorum 指令文件以及範例文件
2. 新增 `bdk quorum network up` 指令
3. 新增 `bdk quorum network down` 指令
4. 新增 `bdk quorum backup export` 指令
5. 新增 `bdk quorum backup import` 指令
6. 修正 `bdk quorum network delete` 未移除舊檔案
7. 修正 `bdk quorum network create` 容器網路未初始化
- `bdk quorum network delete` 未刪除舊節點檔案
- `bdk quorum network create` 需先執行 `docker network create quorum` 的問題
- Quorum 網路備份還原功能請求
* OS: macOS 12.5.1
* Docker Version: 20.10.17

Update: Quorum backup and run

---

src/ui/models/type/ui.type.ts
src/ui/services/commandContext.ts
src/ui/services/containerContext.ts
src/ui/views/app.tsx
src/ui/views/command.tsx
src/ui/views/dockerLogs.tsx
src/ui/views/terminal.tsx

- 新增 `handleSelect` 功能，提供指令選擇
- 處理所選擇指令，目前不支援互動式，只支援預設
- 新增 dockerlogs 列出 container 功能
* OS: macOS 13.4.1(c)
* Docker Version: 20.10.17
- [] 我有在程式碼中提供必要的註解 (I have commented my code, particularly in hard-to-understand areas)

feat: select and excute command

---

.nycrc.json
docs/wallet/COMMANDS.md
docs/wallet/EXAMPLE.md
src/bdk.ts
src/quorum/command/network/create.ts
src/quorum/service/network.ts
src/wallet/command/create.ts
src/wallet/model/type/wallet.type.ts
src/wallet/service/wallet.ts
src/wallet/wallet.ts
test/quorum/service/network.test.ts
test/wallet/service/create.test.ts

Add new category for wallet and create function for ethereum wallet.
* OS: macOS 13.5
* Docker Version: 24.0.6

feat: bdk wallet create

---

src/quorum/model/yaml/docker-compose/explorerDockerComposeYaml.ts

fix explorer indexer error
- #71 
- Explorer useless request
* OS: macOS 13.4.1(c)
* Docker Version: 24.0.5

fix: explorer indexer error

---

.github/workflows/publish-npm-package.yml

- fix npm publish
- [publish-npm-package](https://github.com/cathayddt/bdk/blob/master/.github/workflows/publish-npm-package.yml) npm-registry error
* OS: macOS 13.4.1(c)
* Docker Version: 24.0.6

fix: npm publish config

---

src/quorum/command/network/create.ts
src/quorum/command/network/generate.ts
src/quorum/instance/bdkFile.ts
src/quorum/model/type/network.type.ts
src/quorum/service/network.ts
src/wallet/service/wallet.ts

* refactor `service/createNetwork` service
* add `network-info.json` in bdkFiles
* backup before network create (delete action)
- dashboard need `network-info`
- create delete all file include other function created
* OS: macOS 14.2.1
* NodeJS Version: 9.8.1
* NPM Version: 18.18.2
* Docker Version: 24.0.6

feat: optimize create network

---

src/quorum/model/type/config.type.ts

- [ x ] 遵守 Commit 規範 (follow [commit convention](https://github.com/cathayddt/bdk/blob/master/.github/COMMIT_CONVENTION.md))
- [ x ] 遵守 Contributing 規範 (follow [contributing](https://github.com/cathayddt/bdk/blob/master/.github/CONTRIBUTING.md))
移除了 Quorum 中的 ConfigEnvType 並修改 NodeTypeEnum 的註解 
- [ x ] Bug fix (除錯 non-breaking change which fixes an issue)
* OS: 
* NPM Version:
- [ x ] 我的程式碼遵從此專案的規範 (My code follows the style guidelines of this project)
- [ x ] 我有對於自己的程式碼進行測試檢查 (I have performed a self-review of my own code)
- [ x ] 我有在程式碼中提供必要的註解 (I have commented my code, particularly in hard-to-understand areas)
- [ x ] 我有在文件中進行必要的更動 (I have made corresponding changes to the documentation)
- [ x ] 我的程式碼更動沒有顯著增加錯誤數量 (My …

fix: remove ConfigEnvType from Quorum

---

.github/workflows/test-report.yml
.github/workflows/unit-test.yml
src/eth/service/contract.ts

* OS: Linux 5.15 (WSL2)
* NodeJS Version: 18.13.0
* NPM Version: 8.19.3
* Docker Version: 27.3.1

chore: Insufficient modification permissions
